### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by rodolfovs** [byrobingames/simpleshare#1] opened 2019-01-12 22:03 UTC
Hello,

I am testing the extension and at the time of compiling the error appears as in the image. Any idea what that might be?

![captura de tela 2019-01-12 as 19 59 39](https://user-images.githubusercontent.com/3920814/51078930-bba34d80-16a4-11e9-8326-f6c5a01ee26c.jpg)

**Comment by byrobingames** [comment] 2019-01-12 23:13
Did you update to version 1.9.6?

This error appears when you using version <1.9.5 on Stencyl 3.5.

**Comment by rodolfovs** [comment] 2019-01-13 14:47
Hello Robin,

Actually I was not using the latest version of the extension. As I updated the toolset manager and did not appear the button to update the simple share, I thought it was in the last version, but I updated now manually and it worked.

Another small doubt, I realized that in this version of the extension the shared images are not in the same quality, the borders of the drawings are pixelated, what can be this? It looks like the image has been resized and all pixelated.

**Comment by byrobingames** [comment] 2019-01-13 17:46
Ok think you have not the latest Toolset version. Latest version is 7. 
From version 6 the toolset looks for updates on Github..
https://github.com/byrobingames/byrobintoolsetmanager/releases

I have will take a look at the image change, on my side I saw no difference.. I will come back on that.

Edit: Can you share a screenshot..

**Comment by rodolfovs** [comment] 2019-01-13 19:37
Right, image 1 was taken through the Simple Share extension and picture 2 was taken directly by the print screen function of the cell phone.

![screen1](https://user-images.githubusercontent.com/3920814/51089756-a76d5800-1759-11e9-9024-0a92f721d0ce.png)
![screen2](https://user-images.githubusercontent.com/3920814/51089757-a76d5800-1759-11e9-8992-5e00adf233ae.png)

**Comment by byrobingames** [comment] 2019-01-13 19:55
Ok i see and in the previous version there was no difference right?

I try to look at it this week.

**Comment by rodolfovs** [comment] 2019-01-13 20:04
Yes, in a previous version did not occur this difference, I just do not know which version I used, because it was some time ago.

Thank you for your help!

**Comment by byrobingames** [comment] 2019-01-13 20:30
Ok I was just thinking.. that was on Stencyl 3.4 right. 
This extension uses the IMAGE API from Stencyl, so maybe the problem is with IMAGE API in Stencyl 3.5.

You can test by using IMAGE API screenshot without this extension. And if the result is also different than the issue is in Stencyl 3.5.

If the result is not difference than it should in the simpleshare extension.

Can you test that?

**Comment by rodolfovs** [comment] 2019-01-13 20:43
I just tested, there really is a problem with the Stencyl image API.

I realized that in addition to leaving the pixelated image, it increases the size of the image, so maybe this problem. I picked up the screen image and attached it on the screen itself, and it stayed in a size larger than the screen.

**Comment by byrobingames** [comment] 2019-01-13 20:52
Ok then I advise you to open an issue on Stencyl issue tracker about IMAGE API

I will close this issue now.

**Closed as completed by byrobingames** 2019-01-13 20:52 UTC
